version: '3.8'

services:
  mssql:
    container_name: mssql_container
    build: ./db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
#    ports:
#      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong@Passw0rd -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
      - "3000:3000"
